# PBS
queue: express
ncpus: 4
walltime: 0:10:00
mem: 1GB
jobname: bowl1

# Model
model: mom
exe: mom5_solo
input:
        - INPUT/gotmturb.inp
        - INPUT/grid_spec.nc
        - INPUT/ocean_temp_salt.res.nc
        - INPUT/salt_sfc_restore.nc
        - INPUT/tau.nc
        - INPUT/temp_sfc_restore.nc
        - INPUT/water_flux.nc

runlog: False
metadata: 
    enable: False

# Config
collate: False
