format: yamanifest
version: 1.0
---
work/INPUT/gotmturb.inp:
  fullpath: /g/data/tm70/aph502/bowl1/INPUT/gotmturb.inp
  hashes:
    binhash: 99b94ae6c7ec29d697071906ded3b6d7
    md5: 3016ea3bccf1acd2c18eefdd6dbf02e9
work/INPUT/grid_spec.nc:
  fullpath: /g/data/tm70/aph502/bowl1/INPUT/grid_spec.nc
  hashes:
    binhash: 7cc14daa7a6660e2970ccc8af5dbdecb
    md5: 681e5971847914e6e8fdd2c7f550fe24
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/tm70/aph502/bowl1/INPUT/salt_sfc_restore.nc
  hashes:
    binhash: 3faeccc4850bc16ca3083316f0b9d250
    md5: 649c5a1fb9d00e5b2a0710f78a4c66ec
work/INPUT/tau.nc:
  fullpath: /g/data/tm70/aph502/bowl1/INPUT/tau.nc
  hashes:
    binhash: bcb0e24e788a64335b5fa8c0e697e390
    md5: 5f41e4a0eb88e055c98b9b5a069f8bcc
work/INPUT/temp_sfc_restore.nc:
  fullpath: /g/data/tm70/aph502/bowl1/INPUT/temp_sfc_restore.nc
  hashes:
    binhash: 58adfe38d455dda91069180004062ab1
    md5: b50ce99bfb62b24e79f53afa5d9ef795
work/INPUT/water_flux.nc:
  fullpath: /g/data/tm70/aph502/bowl1/INPUT/water_flux.nc
  hashes:
    binhash: 81747f45f366ab70102bd032df9a5d83
    md5: aec90db5e2083571375d4db5e9d3839f
